# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'budgetWidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'

  # Pods for budgetWidget

end

target 'nubankDailyLimitWidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nubankDailyLimitWidget

end
